### PR TITLE
Relax httparty dependency

### PR DESCRIPTION
**Pull request by mikesaelim**

### CODE REVIEW

**Review by mattyb — APPROVED** [review]
LGTM

**Review by mattyb — CHANGES_REQUESTED** [review]
actually, should we also update travis to test on 2.5.8?

**Comment by mikesaelim** [comment]
Yeah, I'm still working on updating all the ruby versions and development dependencies.  You've come to this httparty too early!

**Comment by mikesaelim** [comment]
@mattyb Can I get another review?

**Review by mattyb — APPROVED** [review]
LGTM!

**Pull request merged**
